---
- name: httpd playbook lesson1 task1
  hosts: nodes
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: delete httpd
    package:
      name: httpd
      state: absent
  - name: delete index.html
    file:
      path: /var/www/html/index.html
      state: absent
  - name: Closing http
    firewalld:
      service: http
      zone: public
      state: disabled
      permanent: yes
      immediate: yes
...
